cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://rafaelms.com.br
file:
  upload-dir: /Users\Rafael\Desktop\UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000 #1 hora
email:
  subject: "Default subject"
  message: "Default message"
spring:
  application:
    name:
      rest-with-spring
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest-with-spring?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: novasenha
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
        show_sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  flyway:
    baseline-on-migrate: true
logging:
  level:
    root: info
spring.doc:
  paths-to-match:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true